# Generated by Django 5.2.5 on 2025-08-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videography',
            name='video',
        ),
        migrations.AddField(
            model_name='videography',
            name='url',
            field=models.URLField(default=1, help_text='Instagram post URL (public), e.g., https://www.instagram.com/p/POST_ID/'),
            preserve_default=False,
        ),
    ]
