# Generated by Django 5.2.5 on 2025-08-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_videography_video_videography_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.AlterModelOptions(
            name='photography',
            options={'ordering': ['-created_at'], 'verbose_name': 'Photography', 'verbose_name_plural': 'Photographies'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='videography',
            options={'ordering': ['-created_at'], 'verbose_name': 'Videography', 'verbose_name_plural': 'Videographies'},
        ),
        migrations.AddField(
            model_name='videography',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='photography',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videography',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videography',
            name='url',
            field=models.URLField(blank=True, help_text='Instagram post URL (public), e.g., https://www.instagram.com/p/POST_ID/', null=True),
        ),
    ]
