# Generated by Django 5.2.5 on 2025-08-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Attachment (optional)'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Attachment URL (optional)'),
        ),
        migrations.AddField(
            model_name='photography',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Image URL'),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_url',
            field=models.URLField(blank=True, null=True, verbose_name='Avatar URL'),
        ),
        migrations.AlterField(
            model_name='photography',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photography/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Project URL'),
        ),
        migrations.AlterField(
            model_name='videography',
            name='url',
            field=models.URLField(blank=True, help_text='Paste a video URL (Cloudinary, YouTube, Instagram, etc.)', null=True, verbose_name='Video URL'),
        ),
    ]
